[build]
	command = "npm run build"
	publish = "dist/"

[build.environment]
	NODE_VERSION = "20"

[[headers]]
	# Define which paths this specific [[headers]] block will cover.
	for = "/*"

	[headers.values]
		Access-Control-Allow-Origin = "*"
		Access-Control-Allow-Headers = "Content-Type"
		Access-Control-Allow-Methods = "GET, POST, OPTIONS"
		Content-Security-Policy = "default-src 'self' app.netlify.com cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com 'unsafe-inline'; img-src 'self' data:;"
		X-Content-Type-Options = "nosniff"
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"
