[build]
	command = "npm run generate"
	publish = "dist/"

[build.environment]
	NODE_VERSION = "16"

[[headers]]
	# Define which paths this specific [[headers]] block will cover.
	for = "/*"

	[headers.values]
		Content-Security-Policy = "default-src 'self' cdn.jsdelivr.net fonts.googleapis.com fonts.gstatic.com 'unsafe-inline'; img-src 'self' data:;"
		X-Content-Type-Options = "nosniff"
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"
